/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClaudeCodeRouteImport } from './routes/claude-code'
import { Route as SuporteRouteImport } from './routes/suporte'
import { Route as TutorialRouteImport } from './routes/tutorial'
import { Route as Claude2IndexRouteImport } from './routes/claude2/index'
import { Route as Claude2ObrigadoRouteImport } from './routes/claude2/obrigado'
import { Route as LojaIndexRouteImport } from './routes/loja/index'
import { Route as LojaSeccaoRouteImport } from './routes/loja/$seccao'
import { Route as LojaClaudeCodeRouteImport } from './routes/loja/claude-code'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClaudeCodeRoute = ClaudeCodeRouteImport.update({
  id: '/claude-code',
  path: '/claude-code',
  getParentRoute: () => rootRouteImport,
} as any)
const SuporteRoute = SuporteRouteImport.update({
  id: '/suporte',
  path: '/suporte',
  getParentRoute: () => rootRouteImport,
} as any)
const TutorialRoute = TutorialRouteImport.update({
  id: '/tutorial',
  path: '/tutorial',
  getParentRoute: () => rootRouteImport,
} as any)
const Claude2IndexRoute = Claude2IndexRouteImport.update({
  id: '/claude2/',
  path: '/claude2/',
  getParentRoute: () => rootRouteImport,
} as any)
const Claude2ObrigadoRoute = Claude2ObrigadoRouteImport.update({
  id: '/claude2/obrigado',
  path: '/claude2/obrigado',
  getParentRoute: () => rootRouteImport,
} as any)
const LojaIndexRoute = LojaIndexRouteImport.update({
  id: '/loja/',
  path: '/loja/',
  getParentRoute: () => rootRouteImport,
} as any)
const LojaSeccaoRoute = LojaSeccaoRouteImport.update({
  id: '/loja/$seccao',
  path: '/loja/$seccao',
  getParentRoute: () => rootRouteImport,
} as any)
const LojaClaudeCodeRoute = LojaClaudeCodeRouteImport.update({
  id: '/loja/claude-code',
  path: '/loja/claude-code',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/claude-code': typeof ClaudeCodeRoute
  '/suporte': typeof SuporteRoute
  '/tutorial': typeof TutorialRoute
  '/claude2/obrigado': typeof Claude2ObrigadoRoute
  '/loja/$seccao': typeof LojaSeccaoRoute
  '/loja/claude-code': typeof LojaClaudeCodeRoute
  '/claude2/': typeof Claude2IndexRoute
  '/loja/': typeof LojaIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/claude-code': typeof ClaudeCodeRoute
  '/suporte': typeof SuporteRoute
  '/tutorial': typeof TutorialRoute
  '/claude2/obrigado': typeof Claude2ObrigadoRoute
  '/loja/$seccao': typeof LojaSeccaoRoute
  '/loja/claude-code': typeof LojaClaudeCodeRoute
  '/claude2': typeof Claude2IndexRoute
  '/loja': typeof LojaIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/claude-code': typeof ClaudeCodeRoute
  '/suporte': typeof SuporteRoute
  '/tutorial': typeof TutorialRoute
  '/claude2/obrigado': typeof Claude2ObrigadoRoute
  '/loja/$seccao': typeof LojaSeccaoRoute
  '/loja/claude-code': typeof LojaClaudeCodeRoute
  '/claude2/': typeof Claude2IndexRoute
  '/loja/': typeof LojaIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/claude-code'
    | '/suporte'
    | '/tutorial'
    | '/claude2/obrigado'
    | '/loja/$seccao'
    | '/loja/claude-code'
    | '/claude2/'
    | '/loja/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/claude-code'
    | '/suporte'
    | '/tutorial'
    | '/claude2/obrigado'
    | '/loja/$seccao'
    | '/loja/claude-code'
    | '/claude2'
    | '/loja'
  id:
    | '__root__'
    | '/'
    | '/claude-code'
    | '/suporte'
    | '/tutorial'
    | '/claude2/obrigado'
    | '/loja/$seccao'
    | '/loja/claude-code'
    | '/claude2/'
    | '/loja/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClaudeCodeRoute: typeof ClaudeCodeRoute
  SuporteRoute: typeof SuporteRoute
  TutorialRoute: typeof TutorialRoute
  Claude2ObrigadoRoute: typeof Claude2ObrigadoRoute
  LojaSeccaoRoute: typeof LojaSeccaoRoute
  LojaClaudeCodeRoute: typeof LojaClaudeCodeRoute
  Claude2IndexRoute: typeof Claude2IndexRoute
  LojaIndexRoute: typeof LojaIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/claude-code': {
      id: '/claude-code'
      path: '/claude-code'
      fullPath: '/claude-code'
      preLoaderRoute: typeof ClaudeCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suporte': {
      id: '/suporte'
      path: '/suporte'
      fullPath: '/suporte'
      preLoaderRoute: typeof SuporteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tutorial': {
      id: '/tutorial'
      path: '/tutorial'
      fullPath: '/tutorial'
      preLoaderRoute: typeof TutorialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/claude2/': {
      id: '/claude2/'
      path: '/claude2'
      fullPath: '/claude2/'
      preLoaderRoute: typeof Claude2IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/claude2/obrigado': {
      id: '/claude2/obrigado'
      path: '/claude2/obrigado'
      fullPath: '/claude2/obrigado'
      preLoaderRoute: typeof Claude2ObrigadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loja/': {
      id: '/loja/'
      path: '/loja'
      fullPath: '/loja/'
      preLoaderRoute: typeof LojaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loja/$seccao': {
      id: '/loja/$seccao'
      path: '/loja/$seccao'
      fullPath: '/loja/$seccao'
      preLoaderRoute: typeof LojaSeccaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loja/claude-code': {
      id: '/loja/claude-code'
      path: '/loja/claude-code'
      fullPath: '/loja/claude-code'
      preLoaderRoute: typeof LojaClaudeCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClaudeCodeRoute: ClaudeCodeRoute,
  SuporteRoute: SuporteRoute,
  TutorialRoute: TutorialRoute,
  Claude2ObrigadoRoute: Claude2ObrigadoRoute,
  LojaSeccaoRoute: LojaSeccaoRoute,
  LojaClaudeCodeRoute: LojaClaudeCodeRoute,
  Claude2IndexRoute: Claude2IndexRoute,
  LojaIndexRoute: LojaIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
